humans:

    # write the images here
    path: replace ./test/
  
    # CSV file with image parameters
    csv: ./test/files.csv
  
    # number of images to generate
    count: 32

    # image style components
    style: still
  
    # image output format
    format: bmp
  
    # image dimensions
    size: 256,192
  
    # projection (frustum or perspective)
    projection: perspective 30.0,4.0/3.0,0.1,100.0
  
    # head position
    head:
        pos:
            x: normal 0.0,0.05
            y: normal 0.0,0.05
            z: normal -0.5,0.3
        dir:
            y: normal 0.0,0.4
            p: normal 0.0,0.4
  
    # left eye heading
    lefteye:
        y: 0.0
        p: 0.0
  
    # right eye heading
    righteye:
        y: 0.0
        p: 0.0
  
    # light source
    light:
        dir:
            y: normal 0.0,0.5
            p: normal 0.7,0.6
        color:
            r: 1.0
            g: 1.0
            b: 1.0
  
    # background parameters
    background: image ./backgrounds/
  
    # ambient color
    ambient:
        r: 0.2
        g: 0.2
        b: 0.2
  
    # skin color
    skin:
        r: normal 0.8,0.1
        g: normal 0.7,0.1
        b: normal 0.6,0.1
  
    # sclera color
    sclera:
        r: 0.8
        g: 0.8
        b: 0.8
  
    # iris color
    iris:
        r: 0.14
        g: 0.14
        b: 0.30
